### ISSUE TITLE
Bundle Error while deploying to iOS Simulator

### ISSUE THREAD

**Issue by Playrom** [teamdigitale/italia-app#163]
I've follwed the contribution guide but I'm receiving this bundle error after compiling the project and running "react-native run-ios"

```
error: bundling failed: Error: Unable to resolve module `../../definitions/backend/Platform` from `/Users/playrom/Sites/italia-app/ts/sagas/notifications.ts`: The module `../../definitions/backend/Platform` could not be found from `/Users/playrom/Sites/italia-app/ts/sagas/notifications.ts`. Indeed, none of these files exist:

  * `/Users/playrom/Sites/italia-app/definitions/backend/Platform(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/playrom/Sites/italia-app/definitions/backend/Platform/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/playrom/Sites/italia-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/Users/playrom/Sites/italia-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/playrom/Sites/italia-app/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/playrom/Sites/italia-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/playrom/Sites/italia-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/playrom/Sites/italia-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/playrom/Sites/italia-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/playrom/Sites/italia-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

```

In order to resolve this error you must run "npm run generate:api-definitions" before, maybe you should add that line on the README.md ?

**Comment by cloudify** [comment]
Thanks @Playrom for the heads up, I've updated the documentation in #164
